// AUTO-GENERATED by tools/gen_schemas.py - do not edit
#pragma once

#include <cstddef>

#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataAck.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataAnimation.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataCamera.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataFormat.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataGeometry.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataInterface.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataMap.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataRPG.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataRPGTmp.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataRpgConstants.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataScenario.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataScript.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataSound.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataTerrain.h"

namespace NDb {

struct SColumnInfo {
    const char* name;
    int type;       // 0=int, 1=bool, 2=float, 3=string, 4=wstring, 5=ref(CPtr<T>)
    int offset;     // offsetof(class, outer_member)
    int subOffset;  // offsetof(struct, sub_member) for nested fields, else 0
    const char* refClass; // for type=5, target record class name (e.g. "CTexture"); else nullptr
};

template<typename T> const SColumnInfo* GetSchemaFor();

// CDBDialog  (from DataAck.cpp:94)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBDialog>() {
    static const SColumnInfo cols[] = {
        { "Code", 3, offsetof(NDb::CDBDialog, szCode), 0, nullptr },  // string
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CDBDialogSeq  (from DataAck.cpp:101)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBDialogSeq>() {
    static const SColumnInfo cols[] = {
        { "DialogID",     0, offsetof(NDb::CDBDialogSeq, nDialogID), 0, nullptr },  // int
        { "AckInfoID",    5, offsetof(NDb::CDBDialogSeq, pAckInfo), 0, "CDBAckInfo" },  // ref
        { "AckInfoOrder", 0, offsetof(NDb::CDBDialogSeq, nAckInfoOrder), 0, nullptr },  // int
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CDBDialogPers  (from DataAck.cpp:110)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBDialogPers>() {
    static const SColumnInfo cols[] = {
        { "PersID", 0, offsetof(NDb::CDBDialogPers, nPersID), 0, nullptr },  // int
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CDBCamera  (from DataCamera.cpp:10)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBCamera>() {
    static const SColumnInfo cols[] = {
        { "Yaw",      2, offsetof(NDb::CDBCamera, fYaw), 0, nullptr },  // float
        { "Pitch",    2, offsetof(NDb::CDBCamera, fPitch), 0, nullptr },  // float
        { "Roll",     2, offsetof(NDb::CDBCamera, fRoll), 0, nullptr },  // float
        { "Distance", 2, offsetof(NDb::CDBCamera, fDistance), 0, nullptr },  // float
        { "AnchorX",  2, offsetof(NDb::CDBCamera, vAnchor), offsetof(CVec3, x), nullptr },  // float
        { "AnchorY",  2, offsetof(NDb::CDBCamera, vAnchor), offsetof(CVec3, y), nullptr },  // float
        { "AnchorZ",  2, offsetof(NDb::CDBCamera, vAnchor), offsetof(CVec3, z), nullptr },  // float
        { "FOV",      2, offsetof(NDb::CDBCamera, fFOV), 0, nullptr },  // float
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CSkeleton  (from DataFormat.cpp:477)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CSkeleton>() {
    static const SColumnInfo cols[] = {
        { "AIMeshLie",    5, offsetof(NDb::CSkeleton, pAIMeshLie), 0, "CAIGeometry" },  // ref
        { "AIMeshCrouch", 5, offsetof(NDb::CSkeleton, pAIMeshCrouch), 0, "CAIGeometry" },  // ref
        { "AIMeshStay",   5, offsetof(NDb::CSkeleton, pAIMeshStay), 0, "CAIGeometry" },  // ref
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CCubeTexture  (from DataFormat.cpp:929)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CCubeTexture>() {
    static const SColumnInfo cols[] = {
        { "PositiveX", 5, offsetof(NDb::CCubeTexture, pPositiveX), 0, "CTexture" },  // ref
        { "PositiveY", 5, offsetof(NDb::CCubeTexture, pPositiveY), 0, "CTexture" },  // ref
        { "PositiveZ", 5, offsetof(NDb::CCubeTexture, pPositiveZ), 0, "CTexture" },  // ref
        { "NegativeX", 5, offsetof(NDb::CCubeTexture, pNegativeX), 0, "CTexture" },  // ref
        { "NegativeY", 5, offsetof(NDb::CCubeTexture, pNegativeY), 0, "CTexture" },  // ref
        { "NegativeZ", 5, offsetof(NDb::CCubeTexture, pNegativeZ), 0, "CTexture" },  // ref
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CBRDF  (from DataFormat.cpp:941)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CBRDF>() {
    static const SColumnInfo cols[] = {
        { "fake", 2, offsetof(NDb::CBRDF, fFake), 0, nullptr },  // float
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CGeometry  (from DataFormat.cpp:1099)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CGeometry>() {
    static const SColumnInfo cols[] = {
        { "AIGeometryID",  5, offsetof(NDb::CGeometry, pAIGeometry), 0, "CAIGeometry" },  // ref
        { "AIGeometry2ID", 5, offsetof(NDb::CGeometry, pAIGeometry2), 0, "CAIGeometry" },  // ref
        { "CenterX",       2, offsetof(NDb::CGeometry, boundCenter), offsetof(CVec3, x), nullptr },  // float
        { "CenterY",       2, offsetof(NDb::CGeometry, boundCenter), offsetof(CVec3, y), nullptr },  // float
        { "CenterZ",       2, offsetof(NDb::CGeometry, boundCenter), offsetof(CVec3, z), nullptr },  // float
        { "SizeX",         2, offsetof(NDb::CGeometry, boundSize), offsetof(CVec3, x), nullptr },  // float
        { "SizeY",         2, offsetof(NDb::CGeometry, boundSize), offsetof(CVec3, y), nullptr },  // float
        { "SizeZ",         2, offsetof(NDb::CGeometry, boundSize), offsetof(CVec3, z), nullptr },  // float
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CTypeface  (from DataFormat.cpp:1123)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CTypeface>() {
    static const SColumnInfo cols[] = {
        { "Name",      3, offsetof(NDb::CTypeface, szName), 0, nullptr },  // string
        { "TextureID", 5, offsetof(NDb::CTypeface, pTexture), 0, "CTexture" },  // ref
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CSpot  (from DataFormat.cpp:1155)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CSpot>() {
    static const SColumnInfo cols[] = {
        { "MaterialID", 5, offsetof(NDb::CSpot, pMaterial), 0, "CTMaterial" },  // ref
        { "RPGArmorID", 5, offsetof(NDb::CSpot, pArmor), 0, "CRPGArmor" },  // ref
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CSound  (from DataFormat.cpp:1251)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CSound>() {
    static const SColumnInfo cols[] = {
        { "Loop",        1, offsetof(NDb::CSound, bLoop), 0, nullptr },  // bool
        { "MinDistance", 2, offsetof(NDb::CSound, fMinDistance), 0, nullptr },  // float
        { "MaxDistance", 2, offsetof(NDb::CSound, fMaxDistance), 0, nullptr },  // float
        { "Priority",    0, offsetof(NDb::CSound, nPriority), 0, nullptr },  // int
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CDebris  (from DataFormat.cpp:1308)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDebris>() {
    static const SColumnInfo cols[] = {
        { "ModelID",          5, offsetof(NDb::CDebris, pModel), 0, "CTRndModel" },  // ref
        { "DebrisMaterialID", 5, offsetof(NDb::CDebris, pDebrisMaterial), 0, "CDebrisMaterial" },  // ref
        { "Volume",           0, offsetof(NDb::CDebris, nVolume), 0, nullptr },  // int
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CHead  (from DataFormat.cpp:1636)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CHead>() {
    static const SColumnInfo cols[] = {
        { "Material0", 5, offsetof(NDb::CHead, pMaterial), 0, "CTMaterial" },  // ref
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CUIContainer  (from DataInterface.cpp:82)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CUIContainer>() {
    static const SColumnInfo cols[] = {
        { "Width",  0, offsetof(NDb::CUIContainer, nWidth), 0, nullptr },  // int
        { "Height", 0, offsetof(NDb::CUIContainer, nHeight), 0, nullptr },  // int
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CGlobalMap  (from DataMap.cpp:79)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CGlobalMap>() {
    static const SColumnInfo cols[] = {
        { "Scenario",   5, offsetof(NDb::CGlobalMap, pScenario), 0, "CDBScenario" },  // ref
        { "Background", 5, offsetof(NDb::CGlobalMap, pBackground), 0, "CUITexture" },  // ref
        { "BaseZoneID", 5, offsetof(NDb::CGlobalMap, pBaseZone), 0, "CDBScenarioZone" },  // ref
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CTemplate  (from DataMap.cpp:104)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CTemplate>() {
    static const SColumnInfo cols[] = {
        { "Width",  0, offsetof(NDb::CTemplate, nWidth), 0, nullptr },  // int
        { "Height", 0, offsetof(NDb::CTemplate, nHeight), 0, nullptr },  // int
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CContainer  (from DataMap.cpp:294)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CContainer>() {
    static const SColumnInfo cols[] = {
        { "ModelID",   5, offsetof(NDb::CContainer, pModel), 0, "CRndContainerModel" },  // ref
        { "VariantID", 5, offsetof(NDb::CContainer, pVariant), 0, "CTemplVariant" },  // ref
        { "Rotation",  0, offsetof(NDb::CContainer, nRotation), 0, nullptr },  // int
        { "PosX",      2, offsetof(NDb::CContainer, ptPos), offsetof(CVec2, x), nullptr },  // float
        { "PosY",      2, offsetof(NDb::CContainer, ptPos), offsetof(CVec2, y), nullptr },  // float
        { "Floor",     0, offsetof(NDb::CContainer, nFloor), 0, nullptr },  // int
        { "DeltaZ",    2, offsetof(NDb::CContainer, fDZ), 0, nullptr },  // float
        { "RoomID",    0, offsetof(NDb::CContainer, nRoomID), 0, nullptr },  // int
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CWallModel  (from DataMap.cpp:385)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CWallModel>() {
    static const SColumnInfo cols[] = {
        { "ModelID", 5, offsetof(NDb::CWallModel, pModel), 0, "CTRndModel" },  // ref
        { "Length",  0, offsetof(NDb::CWallModel, nLength), 0, nullptr },  // int
        { "Width",   2, offsetof(NDb::CWallModel, fWidth), 0, nullptr },  // float
        { "Height",  2, offsetof(NDb::CWallModel, fHeight), 0, nullptr },  // float
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CFloorModel  (from DataMap.cpp:405)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CFloorModel>() {
    static const SColumnInfo cols[] = {
        { "ModelID",  5, offsetof(NDb::CFloorModel, pModel), 0, "CTRndModel" },  // ref
        { "Width",    0, offsetof(NDb::CFloorModel, nWidth), 0, nullptr },  // int
        { "Length",   0, offsetof(NDb::CFloorModel, nLength), 0, nullptr },  // int
        { "Rotation", 0, offsetof(NDb::CFloorModel, nRotation), 0, nullptr },  // int
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CSolidModel  (from DataMap.cpp:425)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CSolidModel>() {
    static const SColumnInfo cols[] = {
        { "ModelID",  5, offsetof(NDb::CSolidModel, pModel), 0, "CTRndModel" },  // ref
        { "Length",   0, offsetof(NDb::CSolidModel, nLength), 0, nullptr },  // int
        { "Width",    0, offsetof(NDb::CSolidModel, nWidth), 0, nullptr },  // int
        { "Rotation", 0, offsetof(NDb::CSolidModel, nRotation), 0, nullptr },  // int
        { "Height",   0, offsetof(NDb::CSolidModel, nHeight), 0, nullptr },  // int
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CWall  (from DataMap.cpp:447)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CWall>() {
    static const SColumnInfo cols[] = {
        { "VariantID",   5, offsetof(NDb::CWall, pVariant), 0, "CTemplVariant" },  // ref
        { "WallModelID", 5, offsetof(NDb::CWall, pModel), 0, "CWallModel" },  // ref
        { "Floor",       0, offsetof(NDb::CWall, nFloor), 0, nullptr },  // int
        { "StartX",      2, offsetof(NDb::CWall, ptStart), offsetof(CTPoint<int>, x), nullptr },  // float
        { "StartY",      2, offsetof(NDb::CWall, ptStart), offsetof(CTPoint<int>, y), nullptr },  // float
        { "EndX",        2, offsetof(NDb::CWall, ptEnd), offsetof(CTPoint<int>, x), nullptr },  // float
        { "EndY",        2, offsetof(NDb::CWall, ptEnd), offsetof(CTPoint<int>, y), nullptr },  // float
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CFloor  (from DataMap.cpp:473)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CFloor>() {
    static const SColumnInfo cols[] = {
        { "VariantID", 5, offsetof(NDb::CFloor, pVariant), 0, "CTemplVariant" },  // ref
        { "ModelID",   5, offsetof(NDb::CFloor, pModel), 0, "CFloorModel" },  // ref
        { "Floor",     0, offsetof(NDb::CFloor, nFloor), 0, nullptr },  // int
        { "Coords",    3, offsetof(NDb::CFloor, szCoords), 0, nullptr },  // string
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CSolid  (from DataMap.cpp:493)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CSolid>() {
    static const SColumnInfo cols[] = {
        { "VariantID", 5, offsetof(NDb::CSolid, pVariant), 0, "CTemplVariant" },  // ref
        { "ModelID",   5, offsetof(NDb::CSolid, pModel), 0, "CSolidModel" },  // ref
        { "Floor",     0, offsetof(NDb::CSolid, nFloor), 0, nullptr },  // int
        { "Coords",    3, offsetof(NDb::CSolid, szCoords), 0, nullptr },  // string
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CRoom  (from DataMap.cpp:513)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRoom>() {
    static const SColumnInfo cols[] = {
        { "VariantID", 5, offsetof(NDb::CRoom, pVariant), 0, "CTemplVariant" },  // ref
        { "ModelID",   0, offsetof(NDb::CRoom, nRoomID), 0, nullptr },  // int
        { "Floor",     0, offsetof(NDb::CRoom, nFloor), 0, nullptr },  // int
        { "Coords",    3, offsetof(NDb::CRoom, szCoords), 0, nullptr },  // string
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CAttribute  (from DataMap.cpp:533)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CAttribute>() {
    static const SColumnInfo cols[] = {
        { "UserName", 3, offsetof(NDb::CAttribute, szName), 0, nullptr },  // string
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CWaypointName  (from DataMap.cpp:681)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CWaypointName>() {
    static const SColumnInfo cols[] = {
        { "UserName", 3, offsetof(NDb::CWaypointName, szName), 0, nullptr },  // string
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CRPGStoreItem  (from DataRPG.cpp:169)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGStoreItem>() {
    static const SColumnInfo cols[] = {
        { "Rating",   0, offsetof(NDb::CRPGStoreItem, nRating), 0, nullptr },  // int
        { "ItemID",   5, offsetof(NDb::CRPGStoreItem, pItem), 0, "CRPGItem" },  // ref
        { "SideID",   5, offsetof(NDb::CRPGStoreItem, pSide), 0, "CSide" },  // ref
        { "Quantity", 2, offsetof(NDb::CRPGStoreItem, fQuantity), 0, nullptr },  // float
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CRPGMaterial  (from DataRPG.cpp:197)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGMaterial>() {
    static const SColumnInfo cols[] = {
        { "Threshold",        0, offsetof(NDb::CRPGMaterial, nThreshold), 0, nullptr },  // int
        { "Density",          2, offsetof(NDb::CRPGMaterial, fDensity), 0, nullptr },  // float
        { "VP",               0, offsetof(NDb::CRPGMaterial, nVP), 0, nullptr },  // int
        { "DR",               0, offsetof(NDb::CRPGMaterial, nDR), 0, nullptr },  // int
        { "Transparency",     2, offsetof(NDb::CRPGMaterial, fTransparency), 0, nullptr },  // float
        { "UltimateMoment",   2, offsetof(NDb::CRPGMaterial, fUltimateMoment), 0, nullptr },  // float
        { "UltimatePressure", 2, offsetof(NDb::CRPGMaterial, fUltimatePresure), 0, nullptr },  // float
        { "Weight",           2, offsetof(NDb::CRPGMaterial, fWeight), 0, nullptr },  // float
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CRPGArmor  (from DataRPG.cpp:211)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGArmor>() {
    static const SColumnInfo cols[] = {
        { "SoundStepID",          5, offsetof(NDb::CRPGArmor, pSoundStep), 0, "CTSound" },  // ref
        { "SoundShotID",          5, offsetof(NDb::CRPGArmor, pSoundShot), 0, "CTSound" },  // ref
        { "ShotEffectID",         5, offsetof(NDb::CRPGArmor, pShotEffect), 0, "CTEffect" },  // ref
        { "AISoundType",          0, offsetof(NDb::CRPGArmor, nAISoundType), 0, nullptr },  // int
        { "RPGMaterialID",        5, offsetof(NDb::CRPGArmor, pMaterial), 0, "CRPGMaterial" },  // ref
        { "GrenadeSoundType",     0, offsetof(NDb::CRPGArmor, nGrenadeSoundType), 0, nullptr },  // int
        { "GrenadeExplosionType", 0, offsetof(NDb::CRPGArmor, nGrenadeExplostionType), 0, nullptr },  // int
        { "ShotMaterial",         5, offsetof(NDb::CRPGArmor, pShotMaterial), 0, "CTMaterial" },  // ref
        { "ShotRadius",           2, offsetof(NDb::CRPGArmor, fShotRadius), 0, nullptr },  // float
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CScript  (from DataRPG.cpp:738)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CScript>() {
    static const SColumnInfo cols[] = {
        { "CodeText", 3, offsetof(NDb::CScript, strCode), 0, nullptr },  // string
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CRPGToHit  (from DataRPG.cpp:805)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGToHit>() {
    static const SColumnInfo cols[] = {
        { "MaxShotsRepeat",             0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMaxShotsRepeat), nullptr },  // int
        { "MaxMoveBonus",               0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMaxMoveBonus), nullptr },  // int
        { "FirstRoundCoeff",            2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fFirstRoundCoeff), nullptr },  // float
        { "MaxBurstStabilize",          0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMaxBurstStabilize), nullptr },  // int
        { "SnipingCoeff",               0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nSnipingCoeff), nullptr },  // int
        { "Area&CoverCoeff",            0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nAreaCoverCoeff), nullptr },  // int
        { "SMaxMove",                   0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nSMaxMove), nullptr },  // int
        { "GreandeBaseCoeff",           2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fGrenadeBaseCoeff), nullptr },  // float
        { "GrenadeSTRCoeff",            2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fGrenadeSTRCoeff), nullptr },  // float
        { "Gravity",                    2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fGravity), nullptr },  // float
        { "GrenadeBaseWeight",          2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fGrenadeBaseWeight), nullptr },  // float
        { "MaxWeightRelation",          2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fMaxWeightRelation), nullptr },  // float
        { "ICModifier",                 2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fICModifier), nullptr },  // float
        { "StrikeAddition",             0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nStrikeAddition), nullptr },  // int
        { "MaxAdditionalStrikes",       0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMaxAdditionalStrikes), nullptr },  // int
        { "MaxAPonStrike",              0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMaxAPonStrike), nullptr },  // int
        { "BackSkillMultiplyer",        2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fBackSkillMult), nullptr },  // float
        { "StanceMultiplyer",           2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fStanceMult), nullptr },  // float
        { "BaseMeleeCritChance",        0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nBaseMeleeCritChance), nullptr },  // int
        { "BaseDamage",                 0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nBaseDamage), nullptr },  // int
        { "StrengthNormalize",          0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nStrengthNormalize), nullptr },  // int
        { "BackCriticalMult",           2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fBackCriticalMult), nullptr },  // float
        { "AttackerMultiplyer",         2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fAttackerMult), nullptr },  // float
        { "DefenderMultiplyer",         2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fDefenderMult), nullptr },  // float
        { "MeleeToHitScaling",          0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMeleeToHitScaling), nullptr },  // int
        { "BaseMeleeToHit",             0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nBaseMeleeToHit), nullptr },  // int
        { "GrenadeWeightScaling",       0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nGrenadeWeightScaling), nullptr },  // int
        { "GrenadeWeightScalingBase",   0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nGrenadeWeightScalingBase), nullptr },  // int
        { "MaxGrenadeWeightDifference", 0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMaxGrenadeWeightDifference), nullptr },  // int
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CRPGAISoundConstants  (from DataRPG.cpp:838)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGAISoundConstants>() {
    static const SColumnInfo cols[] = {
        { "PrecisePositionRadius", 0, offsetof(NDb::CRPGAISoundConstants, constants), offsetof(SAISoundConstants, nPrecisePositionRadius), nullptr },  // int
        { "ExitRadius",            0, offsetof(NDb::CRPGAISoundConstants, constants), offsetof(SAISoundConstants, nExitRadius), nullptr },  // int
        { "BaseProbability",       0, offsetof(NDb::CRPGAISoundConstants, constants), offsetof(SAISoundConstants, nBaseProbability), nullptr },  // int
        { "DistanceCoeff",         0, offsetof(NDb::CRPGAISoundConstants, constants), offsetof(SAISoundConstants, nDistanceCoeff), nullptr },  // int
        { "LoudSound",             0, offsetof(NDb::CRPGAISoundConstants, constants), offsetof(SAISoundConstants, nLoudSound), nullptr },  // int
        { "HideCoeff",             2, offsetof(NDb::CRPGAISoundConstants, constants), offsetof(SAISoundConstants, fHideCoeff), nullptr },  // float
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CRPGInterruptsConstants  (from DataRPG.cpp:848)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGInterruptsConstants>() {
    static const SColumnInfo cols[] = {
        { "BackInterruptsBase",       0, offsetof(NDb::CRPGInterruptsConstants, constants), offsetof(SInterruptsConstants, nBackInterruptsBase), nullptr },  // int
        { "InterruptsBase",           0, offsetof(NDb::CRPGInterruptsConstants, constants), offsetof(SInterruptsConstants, nInterruptsBase), nullptr },  // int
        { "MissedShotInterruptsBase", 0, offsetof(NDb::CRPGInterruptsConstants, constants), offsetof(SInterruptsConstants, nMissedShotInterruptsBase), nullptr },  // int
        { "APInterruptReduction",     2, offsetof(NDb::CRPGInterruptsConstants, constants), offsetof(SInterruptsConstants, fAPInterruptReduction), nullptr },  // float
        { "MinInterruptAP",           0, offsetof(NDb::CRPGInterruptsConstants, constants), offsetof(SInterruptsConstants, nMinInterruptAP), nullptr },  // int
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CDBMinesConstants  (from DataRpgConstants.cpp:12)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBMinesConstants>() {
    static const SColumnInfo cols[] = {
        { "BaseDisarmProb",          0, offsetof(NDb::CDBMinesConstants, nBaseDisarmProb), 0, nullptr },  // int
        { "SpotSkillModif",          0, offsetof(NDb::CDBMinesConstants, nSpotSkillModif), 0, nullptr },  // int
        { "MinerEngineerSkillModif", 0, offsetof(NDb::CDBMinesConstants, nMinerEngineerSkillModif), 0, nullptr },  // int
        { "MineSpotModif",           0, offsetof(NDb::CDBMinesConstants, nMineSpotModif), 0, nullptr },  // int
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CRPGItem2Uniform  (from DataRPGTmp.cpp:45)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGItem2Uniform>() {
    static const SColumnInfo cols[] = {
        { "ItemID",       5, offsetof(NDb::CRPGItem2Uniform, pItem), 0, "CRPGItem" },  // ref
        { "UniformID",    5, offsetof(NDb::CRPGItem2Uniform, pUniform), 0, "CRPGUniform" },  // ref
        { "ModelActive1", 5, offsetof(NDb::CRPGItem2Uniform, pModelActive), 0, "CTRndModel" },  // ref
        { "Model1",       5, offsetof(NDb::CRPGItem2Uniform, pModelInactive), 0, "CTRndModel" },  // ref
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CDBScenarioState  (from DataScenario.cpp:62)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBScenarioState>() {
    static const SColumnInfo cols[] = {
        { "Description", 3, offsetof(NDb::CDBScenarioState, sDescription), 0, nullptr },  // string
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CDBScenario  (from DataScenario.cpp:109)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBScenario>() {
    static const SColumnInfo cols[] = {
        { "Name",        3, offsetof(NDb::CDBScenario, szName), 0, nullptr },  // string
        { "Description", 3, offsetof(NDb::CDBScenario, szDescription), 0, nullptr },  // string
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CDBScenarioObjective2Clue  (from DataScenario.cpp:115)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBScenarioObjective2Clue>() {
    static const SColumnInfo cols[] = {
        { "ObjectiveID", 5, offsetof(NDb::CDBScenarioObjective2Clue, pObjective), 0, "CDBScenarioObjective" },  // ref
        { "ClueID",      5, offsetof(NDb::CDBScenarioObjective2Clue, pClue), 0, "CDBScenarioClue" },  // ref
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// CDBAutoLoadScript  (from DataScript.cpp:10)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBAutoLoadScript>() {
    static const SColumnInfo cols[] = {
        { "FileName", 3, offsetof(NDb::CDBAutoLoadScript, szFileName), 0, nullptr },  // string
        { nullptr, 0, 0, 0, nullptr }  // sentinel
    };
    return cols;
}

// ---------------------------------------------------------------------------
// Schema registry: nTableID -> schema getter
// nTableID is the first arg to REGISTER_DATABASE_CLASS(...) — the SAME key
// used by NDatabase::tables / NDatabase::GetTable(int).
// ---------------------------------------------------------------------------

struct SSchemaEntry {
    int typeID;       // nTableID — matches NDatabase::GetTable() key
    const SColumnInfo* (*getter)();
};

inline const SColumnInfo* getSchemaCTemplate() { return GetSchemaFor<NDb::CTemplate>(); }
inline const SColumnInfo* getSchemaCBRDF() { return GetSchemaFor<NDb::CBRDF>(); }
inline const SColumnInfo* getSchemaCGeometry() { return GetSchemaFor<NDb::CGeometry>(); }
inline const SColumnInfo* getSchemaCTypeface() { return GetSchemaFor<NDb::CTypeface>(); }
inline const SColumnInfo* getSchemaCSkeleton() { return GetSchemaFor<NDb::CSkeleton>(); }
inline const SColumnInfo* getSchemaCGlobalMap() { return GetSchemaFor<NDb::CGlobalMap>(); }
inline const SColumnInfo* getSchemaCWallModel() { return GetSchemaFor<NDb::CWallModel>(); }
inline const SColumnInfo* getSchemaCFloorModel() { return GetSchemaFor<NDb::CFloorModel>(); }
inline const SColumnInfo* getSchemaCWall() { return GetSchemaFor<NDb::CWall>(); }
inline const SColumnInfo* getSchemaCFloor() { return GetSchemaFor<NDb::CFloor>(); }
inline const SColumnInfo* getSchemaCSolidModel() { return GetSchemaFor<NDb::CSolidModel>(); }
inline const SColumnInfo* getSchemaCSolid() { return GetSchemaFor<NDb::CSolid>(); }
inline const SColumnInfo* getSchemaCContainer() { return GetSchemaFor<NDb::CContainer>(); }
inline const SColumnInfo* getSchemaCRoom() { return GetSchemaFor<NDb::CRoom>(); }
inline const SColumnInfo* getSchemaCAttribute() { return GetSchemaFor<NDb::CAttribute>(); }
inline const SColumnInfo* getSchemaCSound() { return GetSchemaFor<NDb::CSound>(); }
inline const SColumnInfo* getSchemaCDebris() { return GetSchemaFor<NDb::CDebris>(); }
inline const SColumnInfo* getSchemaCUIContainer() { return GetSchemaFor<NDb::CUIContainer>(); }
inline const SColumnInfo* getSchemaCCubeTexture() { return GetSchemaFor<NDb::CCubeTexture>(); }
inline const SColumnInfo* getSchemaCRPGToHit() { return GetSchemaFor<NDb::CRPGToHit>(); }
inline const SColumnInfo* getSchemaCWaypointName() { return GetSchemaFor<NDb::CWaypointName>(); }
inline const SColumnInfo* getSchemaCRPGAISoundConstants() { return GetSchemaFor<NDb::CRPGAISoundConstants>(); }
inline const SColumnInfo* getSchemaCHead() { return GetSchemaFor<NDb::CHead>(); }
inline const SColumnInfo* getSchemaCRPGInterruptsConstants() { return GetSchemaFor<NDb::CRPGInterruptsConstants>(); }
inline const SColumnInfo* getSchemaCSpot() { return GetSchemaFor<NDb::CSpot>(); }
inline const SColumnInfo* getSchemaCDBScenarioState() { return GetSchemaFor<NDb::CDBScenarioState>(); }
inline const SColumnInfo* getSchemaCDBScenario() { return GetSchemaFor<NDb::CDBScenario>(); }
inline const SColumnInfo* getSchemaCDBScenarioObjective2Clue() { return GetSchemaFor<NDb::CDBScenarioObjective2Clue>(); }
inline const SColumnInfo* getSchemaCDBCamera() { return GetSchemaFor<NDb::CDBCamera>(); }
inline const SColumnInfo* getSchemaCRPGMaterial() { return GetSchemaFor<NDb::CRPGMaterial>(); }
inline const SColumnInfo* getSchemaCDBAutoLoadScript() { return GetSchemaFor<NDb::CDBAutoLoadScript>(); }
inline const SColumnInfo* getSchemaCDBDialog() { return GetSchemaFor<NDb::CDBDialog>(); }
inline const SColumnInfo* getSchemaCDBDialogSeq() { return GetSchemaFor<NDb::CDBDialogSeq>(); }
inline const SColumnInfo* getSchemaCDBDialogPers() { return GetSchemaFor<NDb::CDBDialogPers>(); }
inline const SColumnInfo* getSchemaCDBMinesConstants() { return GetSchemaFor<NDb::CDBMinesConstants>(); }
inline const SColumnInfo* getSchemaCRPGArmor() { return GetSchemaFor<NDb::CRPGArmor>(); }
inline const SColumnInfo* getSchemaCScript() { return GetSchemaFor<NDb::CScript>(); }
inline const SColumnInfo* getSchemaCRPGItem2Uniform() { return GetSchemaFor<NDb::CRPGItem2Uniform>(); }
inline const SColumnInfo* getSchemaCRPGStoreItem() { return GetSchemaFor<NDb::CRPGStoreItem>(); }

inline const SSchemaEntry* GetAllSchemas(int* outCount) {
    static const SSchemaEntry entries[] = {
        { 0x00000004, &getSchemaCTemplate },  // Templates
        { 0x00000008, &getSchemaCBRDF },  // BRDFs
        { 0x0000000a, &getSchemaCGeometry },  // Geometries
        { 0x0000000c, &getSchemaCTypeface },  // Fonts
        { 0x0000000d, &getSchemaCSkeleton },  // Skeletons
        { 0x00000010, &getSchemaCGlobalMap },  // GlobalMaps
        { 0x00000015, &getSchemaCWallModel },  // WallModels
        { 0x00000016, &getSchemaCFloorModel },  // FloorModels
        { 0x00000017, &getSchemaCWall },  // Walls
        { 0x00000018, &getSchemaCFloor },  // Floors
        { 0x0000001a, &getSchemaCSolidModel },  // SolidModels
        { 0x0000001b, &getSchemaCSolid },  // SolidObjects
        { 0x0000001c, &getSchemaCContainer },  // Containers
        { 0x0000001e, &getSchemaCRoom },  // Rooms
        { 0x00000023, &getSchemaCAttribute },  // Attributes
        { 0x00000025, &getSchemaCSound },  // Sounds
        { 0x00000027, &getSchemaCDebris },  // Debris
        { 0x0000002c, &getSchemaCUIContainer },  // UIContainers
        { 0x00000035, &getSchemaCCubeTexture },  // CubeTextures
        { 0x0000003b, &getSchemaCRPGToHit },  // RPGToHits
        { 0x0000003f, &getSchemaCWaypointName },  // WaypointNames
        { 0x00000044, &getSchemaCRPGAISoundConstants },  // AISoundConstants
        { 0x00000045, &getSchemaCHead },  // Heads
        { 0x00000047, &getSchemaCRPGInterruptsConstants },  // InterruptsConstants
        { 0x0000004e, &getSchemaCSpot },  // Spots
        { 0x00000050, &getSchemaCDBScenarioState },  // ScenarioStates
        { 0x00000053, &getSchemaCDBScenario },  // Scenarios
        { 0x00000054, &getSchemaCDBScenarioObjective2Clue },  // ScenarioObjective2Clues
        { 0x00000058, &getSchemaCDBCamera },  // Cameras
        { 0x0000005a, &getSchemaCRPGMaterial },  // RPGMaterials
        { 0x0000005b, &getSchemaCDBAutoLoadScript },  // AutoLoadScripts
        { 0x00000061, &getSchemaCDBDialog },  // Dialogs
        { 0x00000067, &getSchemaCDBDialogSeq },  // DialogSeqs
        { 0x00000068, &getSchemaCDBDialogPers },  // DialogPers
        { 0x00000069, &getSchemaCDBMinesConstants },  // RPGMinesConstants
        { 0xe0000005, &getSchemaCRPGArmor },  // RPGArmors
        { 0xe000000c, &getSchemaCScript },  // Scripts
        { 0xe0000010, &getSchemaCRPGItem2Uniform },  // RPGItem2Uniforms
        { 0xe0000018, &getSchemaCRPGStoreItem },  // RPGStoreItems
    };
    *outCount = sizeof(entries) / sizeof(entries[0]);
    return entries;
}

// ---------------------------------------------------------------------------
// Lookup: record class name -> nTableID (for type=5 ref resolution)
// ---------------------------------------------------------------------------

inline int GetTableIDForClassName(const char* name) {
    if (!name) return -1;
    struct E { const char* cls; int tid; };
    static const E entries[] = {
        { "CAIGeometry", 0x00000014 },  // AIGeometries
        { "CAISound", 0x00000034 },  // AISounds
        { "CAmbientLight", 0x0000001d },  // AmbientLights
        { "CAnimLight", 0x0000004a },  // Lights
        { "CAnimWeaponType", 0x00000043 },  // AnimWeaponTypes
        { "CAnimation", 0x00000002 },  // Animations
        { "CAttribute", 0x00000023 },  // Attributes
        { "CBRDF", 0x00000008 },  // BRDFs
        { "CChapterMap", 0x0000000f },  // ChapterMaps
        { "CComplexHead", 0x0000004b },  // ComplexHeads
        { "CContainer", 0x0000001c },  // Containers
        { "CCubeTexture", 0x00000035 },  // CubeTextures
        { "CDBAck", 0x00000038 },  // Acks
        { "CDBAckInfo", 0x00000036 },  // AckInfos
        { "CDBAckSequence", 0x00000037 },  // AckSeqs
        { "CDBAutoLoadScript", 0x0000005b },  // AutoLoadScripts
        { "CDBCamera", 0x00000058 },  // Cameras
        { "CDBDialog", 0x00000061 },  // Dialogs
        { "CDBDialogPers", 0x00000068 },  // DialogPers
        { "CDBDialogSeq", 0x00000067 },  // DialogSeqs
        { "CDBDifficulty", 0x00000062 },  // DifficultyConstants
        { "CDBDiplomacy", 0x00000063 },  // Diplomacies
        { "CDBMinesConstants", 0x00000069 },  // RPGMinesConstants
        { "CDBPerk", 0x00000065 },  // RPGPerks
        { "CDBPerkTreeNode", 0x00000066 },  // RPGPerkTreeNodes
        { "CDBScenario", 0x00000053 },  // Scenarios
        { "CDBScenarioClue", 0x00000051 },  // ScenarioClues
        { "CDBScenarioObjective", 0x00000052 },  // ScenarioObjectives
        { "CDBScenarioObjective2Clue", 0x00000054 },  // ScenarioObjective2Clues
        { "CDBScenarioState", 0x00000050 },  // ScenarioStates
        { "CDBScenarioZone", 0x0000004f },  // ScenarioZones
        { "CDebris", 0x00000027 },  // Debris
        { "CDebrisMaterial", 0x00000026 },  // DebrisMaterials
        { "CDoor", 0x0000003d },  // Doors
        { "CEffect", 0x00000041 },  // Effects
        { "CExplosion", 0x0000002a },  // Explosions
        { "CFinalElement", 0x00000007 },  // FinalElements
        { "CFloor", 0x00000018 },  // Floors
        { "CFloorModel", 0x00000016 },  // FloorModels
        { "CGeometry", 0x0000000a },  // Geometries
        { "CGlobalMap", 0x00000010 },  // GlobalMaps
        { "CGrass", 0x00000030 },  // Grass
        { "CGun", 0x0000003e },  // Guns
        { "CHead", 0x00000045 },  // Heads
        { "CIntermediateFloor", 0x00000022 },  // IntermediateFloors
        { "CIntermediateSolid", 0x00000024 },  // IntermediateSolids
        { "CLightInstance", 0x00000049 },  // LightInstances
        { "CMaterial", 0x00000009 },  // Materials
        { "CMusic", 0x0000004c },  // Musics
        { "CNationality", 0x00000060 },  // Nationalities
        { "CPanzerklein", 0x00000057 },  // Panzerkleins
        { "CParticle", 0x00000019 },  // Particles
        { "CParticleInstance", 0x00000040 },  // ParticleInstances
        { "CPassageObject", 0x00000056 },  // PassageObjects
        { "CPlacableObject", 0x0000004d },  // PlacableObjects
        { "CRPGAISoundConstants", 0x00000044 },  // AISoundConstants
        { "CRPGAmmo", 0xe0000006 },  // RPGAmmos
        { "CRPGArmor", 0xe0000005 },  // RPGArmors
        { "CRPGBaseValue", 0xe0000007 },  // RPGBaseValues
        { "CRPGClass", 0xe0000003 },  // RPGClasses
        { "CRPGClip", 0xe0000008 },  // RPGClips
        { "CRPGClip4Pers", 0xe000000b },  // RPGClip4Pers
        { "CRPGCritical", 0x00000033 },  // RPGCriticals
        { "CRPGDmgToArmor", 0x00000048 },  // RPGDmgToArmors
        { "CRPGFirstAid", 0xe0000012 },  // RPGFirstAids
        { "CRPGFirstAid4Pers", 0xe0000013 },  // RPGFirstAid4Pers
        { "CRPGGrenade", 0xe000000d },  // RPGGrenades
        { "CRPGGrenade4Pers", 0xe000000f },  // RPGGrenade4Pers
        { "CRPGInterruptsConstants", 0x00000047 },  // InterruptsConstants
        { "CRPGItem", 0xe0000009 },  // RPGItems
        { "CRPGItem2Uniform", 0xe0000010 },  // RPGItem2Uniforms
        { "CRPGKey", 0xe0000023 },  // RPGKeys
        { "CRPGKey4Pers", 0xe0000024 },  // RPGKey4Pers
        { "CRPGMaterial", 0x0000005a },  // RPGMaterials
        { "CRPGMeleeWeapon", 0xe0000014 },  // RPGMeleeWeapons
        { "CRPGMeleeWeapon4Pers", 0xe0000015 },  // RPGMeleeWeapon4Pers
        { "CRPGMine", 0xe0000019 },  // RPGMines
        { "CRPGMine4Pers", 0xe0000020 },  // RPGMines4Pers
        { "CRPGMineDetector", 0xe0000016 },  // RPGMineDetectors
        { "CRPGMineDetector4Pers", 0xe0000017 },  // RPGMineDetector4Pers
        { "CRPGPers", 0xe0000004 },  // RPGPers
        { "CRPGStoreItem", 0xe0000018 },  // RPGStoreItems
        { "CRPGToHit", 0x0000003b },  // RPGToHits
        { "CRPGTool", 0xe0000021 },  // RPGTools
        { "CRPGTool4Pers", 0xe0000022 },  // RPGTool4Pers
        { "CRPGUniform", 0xe000000e },  // RPGUniforms
        { "CRPGWeapon", 0xe0000002 },  // RPGWeapons
        { "CRPGWeapon4Pers", 0xe000000a },  // RPGWeapon4Pers
        { "CRPGWeaponType", 0xe0000001 },  // RPGWeaponTypes
        { "CRectangle", 0x00000006 },  // Rects
        { "CRndConstructionPart", 0x0000002f },  // ConstructionParts
        { "CRndContainerModel", 0x00000021 },  // ContainerModels
        { "CRndModel", 0x00000001 },  // Models
        { "CRndObject", 0x00000028 },  // Objects
        { "CRndTerrainSpot", 0x00000032 },  // TerrainSpots
        { "CRoom", 0x0000001e },  // Rooms
        { "CScript", 0xe000000c },  // Scripts
        { "CSequence", 0x00000046 },  // HeadSeqs
        { "CSide", 0x0000005f },  // Sides
        { "CSkeleton", 0x0000000d },  // Skeletons
        { "CSolid", 0x0000001b },  // SolidObjects
        { "CSolidModel", 0x0000001a },  // SolidModels
        { "CSound", 0x00000025 },  // Sounds
        { "CSoundEffect", 0x0000005e },  // SoundEffects
        { "CSoundInstance", 0x0000005d },  // SoundInstances
        { "CSoundVariant", 0x00000039 },  // SoundVariants
        { "CSpot", 0x0000004e },  // Spots
        { "CString", 0x0000002d },  // Strings
        { "CTAmbientLight", 0x0000005c },  // AmbientLightTemplates
        { "CTConstructionPart", 0x0000002e },  // ConstructionPartTemplates
        { "CTEffect", 0x00000042 },  // EffectTemplates
        { "CTMaterial", 0x0000001f },  // MaterialTemplates
        { "CTRndModel", 0x00000020 },  // ModelTemplates
        { "CTRndObject", 0x00000029 },  // ObjectTemplates
        { "CTSound", 0x0000003a },  // SoundTemplates
        { "CTemplVariant", 0x00000005 },  // TemplVariants
        { "CTemplate", 0x00000004 },  // Templates
        { "CTerrainTile", 0x0000000e },  // TerrainTiles
        { "CTexture", 0x00000003 },  // Textures
        { "CTranslatedString", 0x00000064 },  // TranslatedStrings
        { "CTypeface", 0x0000000c },  // Fonts
        { "CUIContainer", 0x0000002c },  // UIContainers
        { "CUIControl", 0x0000002b },  // UIControls
        { "CUITexture", 0x00000031 },  // UITextures
        { "CUnit", 0x0000000b },  // Units
        { "CUnitGroup", 0x00000059 },  // UnitGroups
        { "CWall", 0x00000017 },  // Walls
        { "CWallModel", 0x00000015 },  // WallModels
        { "CWaypoint", 0x0000003c },  // Waypoints
        { "CWaypointName", 0x0000003f },  // WaypointNames
    };
    for (size_t i = 0; i < sizeof(entries)/sizeof(entries[0]); ++i) {
        const char* a = entries[i].cls;
        const char* b = name;
        while (*a && *a == *b) { ++a; ++b; }
        if (*a == 0 && *b == 0) return entries[i].tid;
    }
    return -1;
}

} // namespace NDb
