// AUTO-GENERATED by tools/gen_schemas.py - do not edit
#pragma once

#include <cstddef>

#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataAck.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataAnimation.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataCamera.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataFormat.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataGeometry.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataInterface.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataMap.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataRPG.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataRPGTmp.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataRpgConstants.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataScenario.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataScript.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataSound.h"
#include "../../../upstream/Soft/Andy/Jan03/a5dll/DBFormat/DataTerrain.h"

namespace NDb {

struct SColumnInfo {
    const char* name;
    int type;       // 0=int, 1=bool, 2=float, 3=string, 4=wstring, 5=ref(CPtr<T>)
    int offset;     // offsetof(class, outer_member)
    int subOffset;  // offsetof(struct, sub_member) for nested fields, else 0
};

template<typename T> const SColumnInfo* GetSchemaFor();

// CDBDialog  (from DataAck.cpp:94)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBDialog>() {
    static const SColumnInfo cols[] = {
        { "Code", 3, offsetof(NDb::CDBDialog, szCode), 0 },  // string
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CDBDialogSeq  (from DataAck.cpp:101)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBDialogSeq>() {
    static const SColumnInfo cols[] = {
        { "DialogID",     0, offsetof(NDb::CDBDialogSeq, nDialogID), 0 },  // int
        { "AckInfoID",    5, offsetof(NDb::CDBDialogSeq, pAckInfo), 0 },  // ref
        { "AckInfoOrder", 0, offsetof(NDb::CDBDialogSeq, nAckInfoOrder), 0 },  // int
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CDBDialogPers  (from DataAck.cpp:110)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBDialogPers>() {
    static const SColumnInfo cols[] = {
        { "PersID", 0, offsetof(NDb::CDBDialogPers, nPersID), 0 },  // int
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CDBCamera  (from DataCamera.cpp:10)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBCamera>() {
    static const SColumnInfo cols[] = {
        { "Yaw",      2, offsetof(NDb::CDBCamera, fYaw), 0 },  // float
        { "Pitch",    2, offsetof(NDb::CDBCamera, fPitch), 0 },  // float
        { "Roll",     2, offsetof(NDb::CDBCamera, fRoll), 0 },  // float
        { "Distance", 2, offsetof(NDb::CDBCamera, fDistance), 0 },  // float
        { "AnchorX",  2, offsetof(NDb::CDBCamera, vAnchor), offsetof(CVec3, x) },  // float
        { "AnchorY",  2, offsetof(NDb::CDBCamera, vAnchor), offsetof(CVec3, y) },  // float
        { "AnchorZ",  2, offsetof(NDb::CDBCamera, vAnchor), offsetof(CVec3, z) },  // float
        { "FOV",      2, offsetof(NDb::CDBCamera, fFOV), 0 },  // float
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CSkeleton  (from DataFormat.cpp:477)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CSkeleton>() {
    static const SColumnInfo cols[] = {
        { "AIMeshLie",    5, offsetof(NDb::CSkeleton, pAIMeshLie), 0 },  // ref
        { "AIMeshCrouch", 5, offsetof(NDb::CSkeleton, pAIMeshCrouch), 0 },  // ref
        { "AIMeshStay",   5, offsetof(NDb::CSkeleton, pAIMeshStay), 0 },  // ref
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CCubeTexture  (from DataFormat.cpp:929)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CCubeTexture>() {
    static const SColumnInfo cols[] = {
        { "PositiveX", 5, offsetof(NDb::CCubeTexture, pPositiveX), 0 },  // ref
        { "PositiveY", 5, offsetof(NDb::CCubeTexture, pPositiveY), 0 },  // ref
        { "PositiveZ", 5, offsetof(NDb::CCubeTexture, pPositiveZ), 0 },  // ref
        { "NegativeX", 5, offsetof(NDb::CCubeTexture, pNegativeX), 0 },  // ref
        { "NegativeY", 5, offsetof(NDb::CCubeTexture, pNegativeY), 0 },  // ref
        { "NegativeZ", 5, offsetof(NDb::CCubeTexture, pNegativeZ), 0 },  // ref
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CBRDF  (from DataFormat.cpp:941)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CBRDF>() {
    static const SColumnInfo cols[] = {
        { "fake", 2, offsetof(NDb::CBRDF, fFake), 0 },  // float
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CGeometry  (from DataFormat.cpp:1099)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CGeometry>() {
    static const SColumnInfo cols[] = {
        { "AIGeometryID",  5, offsetof(NDb::CGeometry, pAIGeometry), 0 },  // ref
        { "AIGeometry2ID", 5, offsetof(NDb::CGeometry, pAIGeometry2), 0 },  // ref
        { "CenterX",       2, offsetof(NDb::CGeometry, boundCenter), offsetof(CVec3, x) },  // float
        { "CenterY",       2, offsetof(NDb::CGeometry, boundCenter), offsetof(CVec3, y) },  // float
        { "CenterZ",       2, offsetof(NDb::CGeometry, boundCenter), offsetof(CVec3, z) },  // float
        { "SizeX",         2, offsetof(NDb::CGeometry, boundSize), offsetof(CVec3, x) },  // float
        { "SizeY",         2, offsetof(NDb::CGeometry, boundSize), offsetof(CVec3, y) },  // float
        { "SizeZ",         2, offsetof(NDb::CGeometry, boundSize), offsetof(CVec3, z) },  // float
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CTypeface  (from DataFormat.cpp:1123)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CTypeface>() {
    static const SColumnInfo cols[] = {
        { "Name",      3, offsetof(NDb::CTypeface, szName), 0 },  // string
        { "TextureID", 5, offsetof(NDb::CTypeface, pTexture), 0 },  // ref
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CSpot  (from DataFormat.cpp:1155)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CSpot>() {
    static const SColumnInfo cols[] = {
        { "MaterialID", 5, offsetof(NDb::CSpot, pMaterial), 0 },  // ref
        { "RPGArmorID", 5, offsetof(NDb::CSpot, pArmor), 0 },  // ref
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CSound  (from DataFormat.cpp:1251)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CSound>() {
    static const SColumnInfo cols[] = {
        { "Loop",        1, offsetof(NDb::CSound, bLoop), 0 },  // bool
        { "MinDistance", 2, offsetof(NDb::CSound, fMinDistance), 0 },  // float
        { "MaxDistance", 2, offsetof(NDb::CSound, fMaxDistance), 0 },  // float
        { "Priority",    0, offsetof(NDb::CSound, nPriority), 0 },  // int
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CDebris  (from DataFormat.cpp:1308)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDebris>() {
    static const SColumnInfo cols[] = {
        { "ModelID",          5, offsetof(NDb::CDebris, pModel), 0 },  // ref
        { "DebrisMaterialID", 5, offsetof(NDb::CDebris, pDebrisMaterial), 0 },  // ref
        { "Volume",           0, offsetof(NDb::CDebris, nVolume), 0 },  // int
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CHead  (from DataFormat.cpp:1636)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CHead>() {
    static const SColumnInfo cols[] = {
        { "Material0", 5, offsetof(NDb::CHead, pMaterial), 0 },  // ref
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CUIContainer  (from DataInterface.cpp:82)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CUIContainer>() {
    static const SColumnInfo cols[] = {
        { "Width",  0, offsetof(NDb::CUIContainer, nWidth), 0 },  // int
        { "Height", 0, offsetof(NDb::CUIContainer, nHeight), 0 },  // int
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CGlobalMap  (from DataMap.cpp:79)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CGlobalMap>() {
    static const SColumnInfo cols[] = {
        { "Scenario",   5, offsetof(NDb::CGlobalMap, pScenario), 0 },  // ref
        { "Background", 5, offsetof(NDb::CGlobalMap, pBackground), 0 },  // ref
        { "BaseZoneID", 5, offsetof(NDb::CGlobalMap, pBaseZone), 0 },  // ref
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CTemplate  (from DataMap.cpp:104)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CTemplate>() {
    static const SColumnInfo cols[] = {
        { "Width",  0, offsetof(NDb::CTemplate, nWidth), 0 },  // int
        { "Height", 0, offsetof(NDb::CTemplate, nHeight), 0 },  // int
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CContainer  (from DataMap.cpp:294)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CContainer>() {
    static const SColumnInfo cols[] = {
        { "ModelID",   5, offsetof(NDb::CContainer, pModel), 0 },  // ref
        { "VariantID", 5, offsetof(NDb::CContainer, pVariant), 0 },  // ref
        { "Rotation",  0, offsetof(NDb::CContainer, nRotation), 0 },  // int
        { "PosX",      2, offsetof(NDb::CContainer, ptPos), offsetof(CVec2, x) },  // float
        { "PosY",      2, offsetof(NDb::CContainer, ptPos), offsetof(CVec2, y) },  // float
        { "Floor",     0, offsetof(NDb::CContainer, nFloor), 0 },  // int
        { "DeltaZ",    2, offsetof(NDb::CContainer, fDZ), 0 },  // float
        { "RoomID",    0, offsetof(NDb::CContainer, nRoomID), 0 },  // int
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CWallModel  (from DataMap.cpp:385)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CWallModel>() {
    static const SColumnInfo cols[] = {
        { "ModelID", 5, offsetof(NDb::CWallModel, pModel), 0 },  // ref
        { "Length",  0, offsetof(NDb::CWallModel, nLength), 0 },  // int
        { "Width",   2, offsetof(NDb::CWallModel, fWidth), 0 },  // float
        { "Height",  2, offsetof(NDb::CWallModel, fHeight), 0 },  // float
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CFloorModel  (from DataMap.cpp:405)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CFloorModel>() {
    static const SColumnInfo cols[] = {
        { "ModelID",  5, offsetof(NDb::CFloorModel, pModel), 0 },  // ref
        { "Width",    0, offsetof(NDb::CFloorModel, nWidth), 0 },  // int
        { "Length",   0, offsetof(NDb::CFloorModel, nLength), 0 },  // int
        { "Rotation", 0, offsetof(NDb::CFloorModel, nRotation), 0 },  // int
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CSolidModel  (from DataMap.cpp:425)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CSolidModel>() {
    static const SColumnInfo cols[] = {
        { "ModelID",  5, offsetof(NDb::CSolidModel, pModel), 0 },  // ref
        { "Length",   0, offsetof(NDb::CSolidModel, nLength), 0 },  // int
        { "Width",    0, offsetof(NDb::CSolidModel, nWidth), 0 },  // int
        { "Rotation", 0, offsetof(NDb::CSolidModel, nRotation), 0 },  // int
        { "Height",   0, offsetof(NDb::CSolidModel, nHeight), 0 },  // int
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CWall  (from DataMap.cpp:447)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CWall>() {
    static const SColumnInfo cols[] = {
        { "VariantID",   5, offsetof(NDb::CWall, pVariant), 0 },  // ref
        { "WallModelID", 5, offsetof(NDb::CWall, pModel), 0 },  // ref
        { "Floor",       0, offsetof(NDb::CWall, nFloor), 0 },  // int
        { "StartX",      2, offsetof(NDb::CWall, ptStart), offsetof(CTPoint<int>, x) },  // float
        { "StartY",      2, offsetof(NDb::CWall, ptStart), offsetof(CTPoint<int>, y) },  // float
        { "EndX",        2, offsetof(NDb::CWall, ptEnd), offsetof(CTPoint<int>, x) },  // float
        { "EndY",        2, offsetof(NDb::CWall, ptEnd), offsetof(CTPoint<int>, y) },  // float
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CFloor  (from DataMap.cpp:473)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CFloor>() {
    static const SColumnInfo cols[] = {
        { "VariantID", 5, offsetof(NDb::CFloor, pVariant), 0 },  // ref
        { "ModelID",   5, offsetof(NDb::CFloor, pModel), 0 },  // ref
        { "Floor",     0, offsetof(NDb::CFloor, nFloor), 0 },  // int
        { "Coords",    3, offsetof(NDb::CFloor, szCoords), 0 },  // string
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CSolid  (from DataMap.cpp:493)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CSolid>() {
    static const SColumnInfo cols[] = {
        { "VariantID", 5, offsetof(NDb::CSolid, pVariant), 0 },  // ref
        { "ModelID",   5, offsetof(NDb::CSolid, pModel), 0 },  // ref
        { "Floor",     0, offsetof(NDb::CSolid, nFloor), 0 },  // int
        { "Coords",    3, offsetof(NDb::CSolid, szCoords), 0 },  // string
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CRoom  (from DataMap.cpp:513)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRoom>() {
    static const SColumnInfo cols[] = {
        { "VariantID", 5, offsetof(NDb::CRoom, pVariant), 0 },  // ref
        { "ModelID",   0, offsetof(NDb::CRoom, nRoomID), 0 },  // int
        { "Floor",     0, offsetof(NDb::CRoom, nFloor), 0 },  // int
        { "Coords",    3, offsetof(NDb::CRoom, szCoords), 0 },  // string
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CAttribute  (from DataMap.cpp:533)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CAttribute>() {
    static const SColumnInfo cols[] = {
        { "UserName", 3, offsetof(NDb::CAttribute, szName), 0 },  // string
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CWaypointName  (from DataMap.cpp:681)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CWaypointName>() {
    static const SColumnInfo cols[] = {
        { "UserName", 3, offsetof(NDb::CWaypointName, szName), 0 },  // string
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CRPGStoreItem  (from DataRPG.cpp:169)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGStoreItem>() {
    static const SColumnInfo cols[] = {
        { "Rating",   0, offsetof(NDb::CRPGStoreItem, nRating), 0 },  // int
        { "ItemID",   5, offsetof(NDb::CRPGStoreItem, pItem), 0 },  // ref
        { "SideID",   5, offsetof(NDb::CRPGStoreItem, pSide), 0 },  // ref
        { "Quantity", 2, offsetof(NDb::CRPGStoreItem, fQuantity), 0 },  // float
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CRPGMaterial  (from DataRPG.cpp:197)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGMaterial>() {
    static const SColumnInfo cols[] = {
        { "Threshold",        0, offsetof(NDb::CRPGMaterial, nThreshold), 0 },  // int
        { "Density",          2, offsetof(NDb::CRPGMaterial, fDensity), 0 },  // float
        { "VP",               0, offsetof(NDb::CRPGMaterial, nVP), 0 },  // int
        { "DR",               0, offsetof(NDb::CRPGMaterial, nDR), 0 },  // int
        { "Transparency",     2, offsetof(NDb::CRPGMaterial, fTransparency), 0 },  // float
        { "UltimateMoment",   2, offsetof(NDb::CRPGMaterial, fUltimateMoment), 0 },  // float
        { "UltimatePressure", 2, offsetof(NDb::CRPGMaterial, fUltimatePresure), 0 },  // float
        { "Weight",           2, offsetof(NDb::CRPGMaterial, fWeight), 0 },  // float
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CRPGArmor  (from DataRPG.cpp:211)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGArmor>() {
    static const SColumnInfo cols[] = {
        { "SoundStepID",          5, offsetof(NDb::CRPGArmor, pSoundStep), 0 },  // ref
        { "SoundShotID",          5, offsetof(NDb::CRPGArmor, pSoundShot), 0 },  // ref
        { "ShotEffectID",         5, offsetof(NDb::CRPGArmor, pShotEffect), 0 },  // ref
        { "AISoundType",          0, offsetof(NDb::CRPGArmor, nAISoundType), 0 },  // int
        { "RPGMaterialID",        5, offsetof(NDb::CRPGArmor, pMaterial), 0 },  // ref
        { "GrenadeSoundType",     0, offsetof(NDb::CRPGArmor, nGrenadeSoundType), 0 },  // int
        { "GrenadeExplosionType", 0, offsetof(NDb::CRPGArmor, nGrenadeExplostionType), 0 },  // int
        { "ShotMaterial",         5, offsetof(NDb::CRPGArmor, pShotMaterial), 0 },  // ref
        { "ShotRadius",           2, offsetof(NDb::CRPGArmor, fShotRadius), 0 },  // float
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CScript  (from DataRPG.cpp:738)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CScript>() {
    static const SColumnInfo cols[] = {
        { "CodeText", 3, offsetof(NDb::CScript, strCode), 0 },  // string
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CRPGToHit  (from DataRPG.cpp:805)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGToHit>() {
    static const SColumnInfo cols[] = {
        { "MaxShotsRepeat",             0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMaxShotsRepeat) },  // int
        { "MaxMoveBonus",               0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMaxMoveBonus) },  // int
        { "FirstRoundCoeff",            2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fFirstRoundCoeff) },  // float
        { "MaxBurstStabilize",          0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMaxBurstStabilize) },  // int
        { "SnipingCoeff",               0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nSnipingCoeff) },  // int
        { "Area&CoverCoeff",            0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nAreaCoverCoeff) },  // int
        { "SMaxMove",                   0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nSMaxMove) },  // int
        { "GreandeBaseCoeff",           2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fGrenadeBaseCoeff) },  // float
        { "GrenadeSTRCoeff",            2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fGrenadeSTRCoeff) },  // float
        { "Gravity",                    2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fGravity) },  // float
        { "GrenadeBaseWeight",          2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fGrenadeBaseWeight) },  // float
        { "MaxWeightRelation",          2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fMaxWeightRelation) },  // float
        { "ICModifier",                 2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fICModifier) },  // float
        { "StrikeAddition",             0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nStrikeAddition) },  // int
        { "MaxAdditionalStrikes",       0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMaxAdditionalStrikes) },  // int
        { "MaxAPonStrike",              0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMaxAPonStrike) },  // int
        { "BackSkillMultiplyer",        2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fBackSkillMult) },  // float
        { "StanceMultiplyer",           2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fStanceMult) },  // float
        { "BaseMeleeCritChance",        0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nBaseMeleeCritChance) },  // int
        { "BaseDamage",                 0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nBaseDamage) },  // int
        { "StrengthNormalize",          0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nStrengthNormalize) },  // int
        { "BackCriticalMult",           2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fBackCriticalMult) },  // float
        { "AttackerMultiplyer",         2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fAttackerMult) },  // float
        { "DefenderMultiplyer",         2, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, fDefenderMult) },  // float
        { "MeleeToHitScaling",          0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMeleeToHitScaling) },  // int
        { "BaseMeleeToHit",             0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nBaseMeleeToHit) },  // int
        { "GrenadeWeightScaling",       0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nGrenadeWeightScaling) },  // int
        { "GrenadeWeightScalingBase",   0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nGrenadeWeightScalingBase) },  // int
        { "MaxGrenadeWeightDifference", 0, offsetof(NDb::CRPGToHit, constants), offsetof(SToHitConstants, nMaxGrenadeWeightDifference) },  // int
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CRPGAISoundConstants  (from DataRPG.cpp:838)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGAISoundConstants>() {
    static const SColumnInfo cols[] = {
        { "PrecisePositionRadius", 0, offsetof(NDb::CRPGAISoundConstants, constants), offsetof(SAISoundConstants, nPrecisePositionRadius) },  // int
        { "ExitRadius",            0, offsetof(NDb::CRPGAISoundConstants, constants), offsetof(SAISoundConstants, nExitRadius) },  // int
        { "BaseProbability",       0, offsetof(NDb::CRPGAISoundConstants, constants), offsetof(SAISoundConstants, nBaseProbability) },  // int
        { "DistanceCoeff",         0, offsetof(NDb::CRPGAISoundConstants, constants), offsetof(SAISoundConstants, nDistanceCoeff) },  // int
        { "LoudSound",             0, offsetof(NDb::CRPGAISoundConstants, constants), offsetof(SAISoundConstants, nLoudSound) },  // int
        { "HideCoeff",             2, offsetof(NDb::CRPGAISoundConstants, constants), offsetof(SAISoundConstants, fHideCoeff) },  // float
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CRPGInterruptsConstants  (from DataRPG.cpp:848)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGInterruptsConstants>() {
    static const SColumnInfo cols[] = {
        { "BackInterruptsBase",       0, offsetof(NDb::CRPGInterruptsConstants, constants), offsetof(SInterruptsConstants, nBackInterruptsBase) },  // int
        { "InterruptsBase",           0, offsetof(NDb::CRPGInterruptsConstants, constants), offsetof(SInterruptsConstants, nInterruptsBase) },  // int
        { "MissedShotInterruptsBase", 0, offsetof(NDb::CRPGInterruptsConstants, constants), offsetof(SInterruptsConstants, nMissedShotInterruptsBase) },  // int
        { "APInterruptReduction",     2, offsetof(NDb::CRPGInterruptsConstants, constants), offsetof(SInterruptsConstants, fAPInterruptReduction) },  // float
        { "MinInterruptAP",           0, offsetof(NDb::CRPGInterruptsConstants, constants), offsetof(SInterruptsConstants, nMinInterruptAP) },  // int
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CDBMinesConstants  (from DataRpgConstants.cpp:12)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBMinesConstants>() {
    static const SColumnInfo cols[] = {
        { "BaseDisarmProb",          0, offsetof(NDb::CDBMinesConstants, nBaseDisarmProb), 0 },  // int
        { "SpotSkillModif",          0, offsetof(NDb::CDBMinesConstants, nSpotSkillModif), 0 },  // int
        { "MinerEngineerSkillModif", 0, offsetof(NDb::CDBMinesConstants, nMinerEngineerSkillModif), 0 },  // int
        { "MineSpotModif",           0, offsetof(NDb::CDBMinesConstants, nMineSpotModif), 0 },  // int
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CRPGItem2Uniform  (from DataRPGTmp.cpp:45)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CRPGItem2Uniform>() {
    static const SColumnInfo cols[] = {
        { "ItemID",       5, offsetof(NDb::CRPGItem2Uniform, pItem), 0 },  // ref
        { "UniformID",    5, offsetof(NDb::CRPGItem2Uniform, pUniform), 0 },  // ref
        { "ModelActive1", 5, offsetof(NDb::CRPGItem2Uniform, pModelActive), 0 },  // ref
        { "Model1",       5, offsetof(NDb::CRPGItem2Uniform, pModelInactive), 0 },  // ref
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CDBScenarioState  (from DataScenario.cpp:62)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBScenarioState>() {
    static const SColumnInfo cols[] = {
        { "Description", 3, offsetof(NDb::CDBScenarioState, sDescription), 0 },  // string
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CDBScenario  (from DataScenario.cpp:109)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBScenario>() {
    static const SColumnInfo cols[] = {
        { "Name",        3, offsetof(NDb::CDBScenario, szName), 0 },  // string
        { "Description", 3, offsetof(NDb::CDBScenario, szDescription), 0 },  // string
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CDBScenarioObjective2Clue  (from DataScenario.cpp:115)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBScenarioObjective2Clue>() {
    static const SColumnInfo cols[] = {
        { "ObjectiveID", 5, offsetof(NDb::CDBScenarioObjective2Clue, pObjective), 0 },  // ref
        { "ClueID",      5, offsetof(NDb::CDBScenarioObjective2Clue, pClue), 0 },  // ref
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// CDBAutoLoadScript  (from DataScript.cpp:10)
template<> inline const SColumnInfo* GetSchemaFor<NDb::CDBAutoLoadScript>() {
    static const SColumnInfo cols[] = {
        { "FileName", 3, offsetof(NDb::CDBAutoLoadScript, szFileName), 0 },  // string
        { nullptr, 0, 0, 0 }  // sentinel
    };
    return cols;
}

// ---------------------------------------------------------------------------
// Schema registry: nTableID -> schema getter
// nTableID is the first arg to REGISTER_DATABASE_CLASS(...) — the SAME key
// used by NDatabase::tables / NDatabase::GetTable(int).
// ---------------------------------------------------------------------------

struct SSchemaEntry {
    int typeID;       // nTableID — matches NDatabase::GetTable() key
    const SColumnInfo* (*getter)();
};

inline const SColumnInfo* getSchemaCTemplate() { return GetSchemaFor<NDb::CTemplate>(); }
inline const SColumnInfo* getSchemaCBRDF() { return GetSchemaFor<NDb::CBRDF>(); }
inline const SColumnInfo* getSchemaCGeometry() { return GetSchemaFor<NDb::CGeometry>(); }
inline const SColumnInfo* getSchemaCTypeface() { return GetSchemaFor<NDb::CTypeface>(); }
inline const SColumnInfo* getSchemaCSkeleton() { return GetSchemaFor<NDb::CSkeleton>(); }
inline const SColumnInfo* getSchemaCGlobalMap() { return GetSchemaFor<NDb::CGlobalMap>(); }
inline const SColumnInfo* getSchemaCWallModel() { return GetSchemaFor<NDb::CWallModel>(); }
inline const SColumnInfo* getSchemaCFloorModel() { return GetSchemaFor<NDb::CFloorModel>(); }
inline const SColumnInfo* getSchemaCWall() { return GetSchemaFor<NDb::CWall>(); }
inline const SColumnInfo* getSchemaCFloor() { return GetSchemaFor<NDb::CFloor>(); }
inline const SColumnInfo* getSchemaCSolidModel() { return GetSchemaFor<NDb::CSolidModel>(); }
inline const SColumnInfo* getSchemaCSolid() { return GetSchemaFor<NDb::CSolid>(); }
inline const SColumnInfo* getSchemaCContainer() { return GetSchemaFor<NDb::CContainer>(); }
inline const SColumnInfo* getSchemaCRoom() { return GetSchemaFor<NDb::CRoom>(); }
inline const SColumnInfo* getSchemaCAttribute() { return GetSchemaFor<NDb::CAttribute>(); }
inline const SColumnInfo* getSchemaCSound() { return GetSchemaFor<NDb::CSound>(); }
inline const SColumnInfo* getSchemaCDebris() { return GetSchemaFor<NDb::CDebris>(); }
inline const SColumnInfo* getSchemaCUIContainer() { return GetSchemaFor<NDb::CUIContainer>(); }
inline const SColumnInfo* getSchemaCCubeTexture() { return GetSchemaFor<NDb::CCubeTexture>(); }
inline const SColumnInfo* getSchemaCRPGToHit() { return GetSchemaFor<NDb::CRPGToHit>(); }
inline const SColumnInfo* getSchemaCWaypointName() { return GetSchemaFor<NDb::CWaypointName>(); }
inline const SColumnInfo* getSchemaCRPGAISoundConstants() { return GetSchemaFor<NDb::CRPGAISoundConstants>(); }
inline const SColumnInfo* getSchemaCHead() { return GetSchemaFor<NDb::CHead>(); }
inline const SColumnInfo* getSchemaCRPGInterruptsConstants() { return GetSchemaFor<NDb::CRPGInterruptsConstants>(); }
inline const SColumnInfo* getSchemaCSpot() { return GetSchemaFor<NDb::CSpot>(); }
inline const SColumnInfo* getSchemaCDBScenarioState() { return GetSchemaFor<NDb::CDBScenarioState>(); }
inline const SColumnInfo* getSchemaCDBScenario() { return GetSchemaFor<NDb::CDBScenario>(); }
inline const SColumnInfo* getSchemaCDBScenarioObjective2Clue() { return GetSchemaFor<NDb::CDBScenarioObjective2Clue>(); }
inline const SColumnInfo* getSchemaCDBCamera() { return GetSchemaFor<NDb::CDBCamera>(); }
inline const SColumnInfo* getSchemaCRPGMaterial() { return GetSchemaFor<NDb::CRPGMaterial>(); }
inline const SColumnInfo* getSchemaCDBAutoLoadScript() { return GetSchemaFor<NDb::CDBAutoLoadScript>(); }
inline const SColumnInfo* getSchemaCDBDialog() { return GetSchemaFor<NDb::CDBDialog>(); }
inline const SColumnInfo* getSchemaCDBDialogSeq() { return GetSchemaFor<NDb::CDBDialogSeq>(); }
inline const SColumnInfo* getSchemaCDBDialogPers() { return GetSchemaFor<NDb::CDBDialogPers>(); }
inline const SColumnInfo* getSchemaCDBMinesConstants() { return GetSchemaFor<NDb::CDBMinesConstants>(); }
inline const SColumnInfo* getSchemaCRPGArmor() { return GetSchemaFor<NDb::CRPGArmor>(); }
inline const SColumnInfo* getSchemaCScript() { return GetSchemaFor<NDb::CScript>(); }
inline const SColumnInfo* getSchemaCRPGItem2Uniform() { return GetSchemaFor<NDb::CRPGItem2Uniform>(); }
inline const SColumnInfo* getSchemaCRPGStoreItem() { return GetSchemaFor<NDb::CRPGStoreItem>(); }

inline const SSchemaEntry* GetAllSchemas(int* outCount) {
    static const SSchemaEntry entries[] = {
        { 0x00000004, &getSchemaCTemplate },  // Templates
        { 0x00000008, &getSchemaCBRDF },  // BRDFs
        { 0x0000000a, &getSchemaCGeometry },  // Geometries
        { 0x0000000c, &getSchemaCTypeface },  // Fonts
        { 0x0000000d, &getSchemaCSkeleton },  // Skeletons
        { 0x00000010, &getSchemaCGlobalMap },  // GlobalMaps
        { 0x00000015, &getSchemaCWallModel },  // WallModels
        { 0x00000016, &getSchemaCFloorModel },  // FloorModels
        { 0x00000017, &getSchemaCWall },  // Walls
        { 0x00000018, &getSchemaCFloor },  // Floors
        { 0x0000001a, &getSchemaCSolidModel },  // SolidModels
        { 0x0000001b, &getSchemaCSolid },  // SolidObjects
        { 0x0000001c, &getSchemaCContainer },  // Containers
        { 0x0000001e, &getSchemaCRoom },  // Rooms
        { 0x00000023, &getSchemaCAttribute },  // Attributes
        { 0x00000025, &getSchemaCSound },  // Sounds
        { 0x00000027, &getSchemaCDebris },  // Debris
        { 0x0000002c, &getSchemaCUIContainer },  // UIContainers
        { 0x00000035, &getSchemaCCubeTexture },  // CubeTextures
        { 0x0000003b, &getSchemaCRPGToHit },  // RPGToHits
        { 0x0000003f, &getSchemaCWaypointName },  // WaypointNames
        { 0x00000044, &getSchemaCRPGAISoundConstants },  // AISoundConstants
        { 0x00000045, &getSchemaCHead },  // Heads
        { 0x00000047, &getSchemaCRPGInterruptsConstants },  // InterruptsConstants
        { 0x0000004e, &getSchemaCSpot },  // Spots
        { 0x00000050, &getSchemaCDBScenarioState },  // ScenarioStates
        { 0x00000053, &getSchemaCDBScenario },  // Scenarios
        { 0x00000054, &getSchemaCDBScenarioObjective2Clue },  // ScenarioObjective2Clues
        { 0x00000058, &getSchemaCDBCamera },  // Cameras
        { 0x0000005a, &getSchemaCRPGMaterial },  // RPGMaterials
        { 0x0000005b, &getSchemaCDBAutoLoadScript },  // AutoLoadScripts
        { 0x00000061, &getSchemaCDBDialog },  // Dialogs
        { 0x00000067, &getSchemaCDBDialogSeq },  // DialogSeqs
        { 0x00000068, &getSchemaCDBDialogPers },  // DialogPers
        { 0x00000069, &getSchemaCDBMinesConstants },  // RPGMinesConstants
        { 0xe0000005, &getSchemaCRPGArmor },  // RPGArmors
        { 0xe000000c, &getSchemaCScript },  // Scripts
        { 0xe0000010, &getSchemaCRPGItem2Uniform },  // RPGItem2Uniforms
        { 0xe0000018, &getSchemaCRPGStoreItem },  // RPGStoreItems
    };
    *outCount = sizeof(entries) / sizeof(entries[0]);
    return entries;
}

} // namespace NDb
