// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SAVEV1_SILENT_STORM_SAVE_FB_H_
#define FLATBUFFERS_GENERATED_SAVEV1_SILENT_STORM_SAVE_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace silent_storm {
namespace save {
namespace fb {

struct Vec3;
struct Vec3Builder;

struct KeyValue;
struct KeyValueBuilder;

struct Unit;
struct UnitBuilder;

struct Mission;
struct MissionBuilder;

struct Save;
struct SaveBuilder;

struct Vec3 FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
};

struct Vec3Builder {
  typedef Vec3 Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3::VT_Z, z, 0.0f);
  }
  explicit Vec3Builder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3> CreateVec3(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3Builder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct KeyValue FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KeyValueBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct KeyValueBuilder {
  typedef KeyValue Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(KeyValue::VT_KEY, key);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(KeyValue::VT_VALUE, value);
  }
  explicit KeyValueBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KeyValue> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KeyValue>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KeyValue> CreateKeyValue(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  KeyValueBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<KeyValue> CreateKeyValueDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    const char *value = nullptr) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return silent_storm::save::fb::CreateKeyValue(
      _fbb,
      key__,
      value__);
}

struct Unit FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UnitBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_ARCHETYPE_ID = 8,
    VT_POSITION = 10,
    VT_ROTATION = 12,
    VT_HP = 14,
    VT_HP_MAX = 16,
    VT_AP = 18,
    VT_AP_MAX = 20,
    VT_SIDE = 22,
    VT_INVENTORY_ITEM_IDS = 24,
    VT_PERKS = 26,
    VT_STATE_FLAGS = 28
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t archetype_id() const {
    return GetField<uint32_t>(VT_ARCHETYPE_ID, 0);
  }
  const silent_storm::save::fb::Vec3 *position() const {
    return GetPointer<const silent_storm::save::fb::Vec3 *>(VT_POSITION);
  }
  float rotation() const {
    return GetField<float>(VT_ROTATION, 0.0f);
  }
  int32_t hp() const {
    return GetField<int32_t>(VT_HP, 0);
  }
  int32_t hp_max() const {
    return GetField<int32_t>(VT_HP_MAX, 0);
  }
  int32_t ap() const {
    return GetField<int32_t>(VT_AP, 0);
  }
  int32_t ap_max() const {
    return GetField<int32_t>(VT_AP_MAX, 0);
  }
  uint8_t side() const {
    return GetField<uint8_t>(VT_SIDE, 0);
  }
  const ::flatbuffers::Vector<uint32_t> *inventory_item_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INVENTORY_ITEM_IDS);
  }
  const ::flatbuffers::Vector<uint16_t> *perks() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_PERKS);
  }
  uint32_t state_flags() const {
    return GetField<uint32_t>(VT_STATE_FLAGS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_ARCHETYPE_ID, 4) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyField<float>(verifier, VT_ROTATION, 4) &&
           VerifyField<int32_t>(verifier, VT_HP, 4) &&
           VerifyField<int32_t>(verifier, VT_HP_MAX, 4) &&
           VerifyField<int32_t>(verifier, VT_AP, 4) &&
           VerifyField<int32_t>(verifier, VT_AP_MAX, 4) &&
           VerifyField<uint8_t>(verifier, VT_SIDE, 1) &&
           VerifyOffset(verifier, VT_INVENTORY_ITEM_IDS) &&
           verifier.VerifyVector(inventory_item_ids()) &&
           VerifyOffset(verifier, VT_PERKS) &&
           verifier.VerifyVector(perks()) &&
           VerifyField<uint32_t>(verifier, VT_STATE_FLAGS, 4) &&
           verifier.EndTable();
  }
};

struct UnitBuilder {
  typedef Unit Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(Unit::VT_ID, id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Unit::VT_NAME, name);
  }
  void add_archetype_id(uint32_t archetype_id) {
    fbb_.AddElement<uint32_t>(Unit::VT_ARCHETYPE_ID, archetype_id, 0);
  }
  void add_position(::flatbuffers::Offset<silent_storm::save::fb::Vec3> position) {
    fbb_.AddOffset(Unit::VT_POSITION, position);
  }
  void add_rotation(float rotation) {
    fbb_.AddElement<float>(Unit::VT_ROTATION, rotation, 0.0f);
  }
  void add_hp(int32_t hp) {
    fbb_.AddElement<int32_t>(Unit::VT_HP, hp, 0);
  }
  void add_hp_max(int32_t hp_max) {
    fbb_.AddElement<int32_t>(Unit::VT_HP_MAX, hp_max, 0);
  }
  void add_ap(int32_t ap) {
    fbb_.AddElement<int32_t>(Unit::VT_AP, ap, 0);
  }
  void add_ap_max(int32_t ap_max) {
    fbb_.AddElement<int32_t>(Unit::VT_AP_MAX, ap_max, 0);
  }
  void add_side(uint8_t side) {
    fbb_.AddElement<uint8_t>(Unit::VT_SIDE, side, 0);
  }
  void add_inventory_item_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> inventory_item_ids) {
    fbb_.AddOffset(Unit::VT_INVENTORY_ITEM_IDS, inventory_item_ids);
  }
  void add_perks(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> perks) {
    fbb_.AddOffset(Unit::VT_PERKS, perks);
  }
  void add_state_flags(uint32_t state_flags) {
    fbb_.AddElement<uint32_t>(Unit::VT_STATE_FLAGS, state_flags, 0);
  }
  explicit UnitBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Unit> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Unit>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Unit> CreateUnit(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint32_t archetype_id = 0,
    ::flatbuffers::Offset<silent_storm::save::fb::Vec3> position = 0,
    float rotation = 0.0f,
    int32_t hp = 0,
    int32_t hp_max = 0,
    int32_t ap = 0,
    int32_t ap_max = 0,
    uint8_t side = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> inventory_item_ids = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> perks = 0,
    uint32_t state_flags = 0) {
  UnitBuilder builder_(_fbb);
  builder_.add_state_flags(state_flags);
  builder_.add_perks(perks);
  builder_.add_inventory_item_ids(inventory_item_ids);
  builder_.add_ap_max(ap_max);
  builder_.add_ap(ap);
  builder_.add_hp_max(hp_max);
  builder_.add_hp(hp);
  builder_.add_rotation(rotation);
  builder_.add_position(position);
  builder_.add_archetype_id(archetype_id);
  builder_.add_name(name);
  builder_.add_id(id);
  builder_.add_side(side);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Unit> CreateUnitDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    const char *name = nullptr,
    uint32_t archetype_id = 0,
    ::flatbuffers::Offset<silent_storm::save::fb::Vec3> position = 0,
    float rotation = 0.0f,
    int32_t hp = 0,
    int32_t hp_max = 0,
    int32_t ap = 0,
    int32_t ap_max = 0,
    uint8_t side = 0,
    const std::vector<uint32_t> *inventory_item_ids = nullptr,
    const std::vector<uint16_t> *perks = nullptr,
    uint32_t state_flags = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto inventory_item_ids__ = inventory_item_ids ? _fbb.CreateVector<uint32_t>(*inventory_item_ids) : 0;
  auto perks__ = perks ? _fbb.CreateVector<uint16_t>(*perks) : 0;
  return silent_storm::save::fb::CreateUnit(
      _fbb,
      id,
      name__,
      archetype_id,
      position,
      rotation,
      hp,
      hp_max,
      ap,
      ap_max,
      side,
      inventory_item_ids__,
      perks__,
      state_flags);
}

struct Mission FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MissionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_MAP_PATH = 6,
    VT_TURN_COUNTER = 8,
    VT_ACTIVE_SIDE = 10,
    VT_OBJECTIVES_COMPLETE = 12,
    VT_OBJECTIVES_FAILED = 14
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *map_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MAP_PATH);
  }
  uint32_t turn_counter() const {
    return GetField<uint32_t>(VT_TURN_COUNTER, 0);
  }
  uint8_t active_side() const {
    return GetField<uint8_t>(VT_ACTIVE_SIDE, 0);
  }
  const ::flatbuffers::Vector<uint32_t> *objectives_complete() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_OBJECTIVES_COMPLETE);
  }
  const ::flatbuffers::Vector<uint32_t> *objectives_failed() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_OBJECTIVES_FAILED);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_MAP_PATH) &&
           verifier.VerifyString(map_path()) &&
           VerifyField<uint32_t>(verifier, VT_TURN_COUNTER, 4) &&
           VerifyField<uint8_t>(verifier, VT_ACTIVE_SIDE, 1) &&
           VerifyOffset(verifier, VT_OBJECTIVES_COMPLETE) &&
           verifier.VerifyVector(objectives_complete()) &&
           VerifyOffset(verifier, VT_OBJECTIVES_FAILED) &&
           verifier.VerifyVector(objectives_failed()) &&
           verifier.EndTable();
  }
};

struct MissionBuilder {
  typedef Mission Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(Mission::VT_ID, id);
  }
  void add_map_path(::flatbuffers::Offset<::flatbuffers::String> map_path) {
    fbb_.AddOffset(Mission::VT_MAP_PATH, map_path);
  }
  void add_turn_counter(uint32_t turn_counter) {
    fbb_.AddElement<uint32_t>(Mission::VT_TURN_COUNTER, turn_counter, 0);
  }
  void add_active_side(uint8_t active_side) {
    fbb_.AddElement<uint8_t>(Mission::VT_ACTIVE_SIDE, active_side, 0);
  }
  void add_objectives_complete(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> objectives_complete) {
    fbb_.AddOffset(Mission::VT_OBJECTIVES_COMPLETE, objectives_complete);
  }
  void add_objectives_failed(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> objectives_failed) {
    fbb_.AddOffset(Mission::VT_OBJECTIVES_FAILED, objectives_failed);
  }
  explicit MissionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Mission> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Mission>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Mission> CreateMission(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> map_path = 0,
    uint32_t turn_counter = 0,
    uint8_t active_side = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> objectives_complete = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> objectives_failed = 0) {
  MissionBuilder builder_(_fbb);
  builder_.add_objectives_failed(objectives_failed);
  builder_.add_objectives_complete(objectives_complete);
  builder_.add_turn_counter(turn_counter);
  builder_.add_map_path(map_path);
  builder_.add_id(id);
  builder_.add_active_side(active_side);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Mission> CreateMissionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *map_path = nullptr,
    uint32_t turn_counter = 0,
    uint8_t active_side = 0,
    const std::vector<uint32_t> *objectives_complete = nullptr,
    const std::vector<uint32_t> *objectives_failed = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto map_path__ = map_path ? _fbb.CreateString(map_path) : 0;
  auto objectives_complete__ = objectives_complete ? _fbb.CreateVector<uint32_t>(*objectives_complete) : 0;
  auto objectives_failed__ = objectives_failed ? _fbb.CreateVector<uint32_t>(*objectives_failed) : 0;
  return silent_storm::save::fb::CreateMission(
      _fbb,
      id__,
      map_path__,
      turn_counter,
      active_side,
      objectives_complete__,
      objectives_failed__);
}

struct Save FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SaveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCHEMA_VERSION = 4,
    VT_TIMESTAMP_UNIX = 6,
    VT_SLOT_NAME = 8,
    VT_MISSION = 10,
    VT_UNITS = 12,
    VT_RNG_SEED = 14,
    VT_EXTRAS = 16
  };
  uint32_t schema_version() const {
    return GetField<uint32_t>(VT_SCHEMA_VERSION, 1);
  }
  uint64_t timestamp_unix() const {
    return GetField<uint64_t>(VT_TIMESTAMP_UNIX, 0);
  }
  const ::flatbuffers::String *slot_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SLOT_NAME);
  }
  const silent_storm::save::fb::Mission *mission() const {
    return GetPointer<const silent_storm::save::fb::Mission *>(VT_MISSION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<silent_storm::save::fb::Unit>> *units() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<silent_storm::save::fb::Unit>> *>(VT_UNITS);
  }
  uint64_t rng_seed() const {
    return GetField<uint64_t>(VT_RNG_SEED, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<silent_storm::save::fb::KeyValue>> *extras() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<silent_storm::save::fb::KeyValue>> *>(VT_EXTRAS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SCHEMA_VERSION, 4) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP_UNIX, 8) &&
           VerifyOffset(verifier, VT_SLOT_NAME) &&
           verifier.VerifyString(slot_name()) &&
           VerifyOffset(verifier, VT_MISSION) &&
           verifier.VerifyTable(mission()) &&
           VerifyOffset(verifier, VT_UNITS) &&
           verifier.VerifyVector(units()) &&
           verifier.VerifyVectorOfTables(units()) &&
           VerifyField<uint64_t>(verifier, VT_RNG_SEED, 8) &&
           VerifyOffset(verifier, VT_EXTRAS) &&
           verifier.VerifyVector(extras()) &&
           verifier.VerifyVectorOfTables(extras()) &&
           verifier.EndTable();
  }
};

struct SaveBuilder {
  typedef Save Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_schema_version(uint32_t schema_version) {
    fbb_.AddElement<uint32_t>(Save::VT_SCHEMA_VERSION, schema_version, 1);
  }
  void add_timestamp_unix(uint64_t timestamp_unix) {
    fbb_.AddElement<uint64_t>(Save::VT_TIMESTAMP_UNIX, timestamp_unix, 0);
  }
  void add_slot_name(::flatbuffers::Offset<::flatbuffers::String> slot_name) {
    fbb_.AddOffset(Save::VT_SLOT_NAME, slot_name);
  }
  void add_mission(::flatbuffers::Offset<silent_storm::save::fb::Mission> mission) {
    fbb_.AddOffset(Save::VT_MISSION, mission);
  }
  void add_units(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<silent_storm::save::fb::Unit>>> units) {
    fbb_.AddOffset(Save::VT_UNITS, units);
  }
  void add_rng_seed(uint64_t rng_seed) {
    fbb_.AddElement<uint64_t>(Save::VT_RNG_SEED, rng_seed, 0);
  }
  void add_extras(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<silent_storm::save::fb::KeyValue>>> extras) {
    fbb_.AddOffset(Save::VT_EXTRAS, extras);
  }
  explicit SaveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Save> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Save>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Save> CreateSave(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t schema_version = 1,
    uint64_t timestamp_unix = 0,
    ::flatbuffers::Offset<::flatbuffers::String> slot_name = 0,
    ::flatbuffers::Offset<silent_storm::save::fb::Mission> mission = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<silent_storm::save::fb::Unit>>> units = 0,
    uint64_t rng_seed = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<silent_storm::save::fb::KeyValue>>> extras = 0) {
  SaveBuilder builder_(_fbb);
  builder_.add_rng_seed(rng_seed);
  builder_.add_timestamp_unix(timestamp_unix);
  builder_.add_extras(extras);
  builder_.add_units(units);
  builder_.add_mission(mission);
  builder_.add_slot_name(slot_name);
  builder_.add_schema_version(schema_version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Save> CreateSaveDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t schema_version = 1,
    uint64_t timestamp_unix = 0,
    const char *slot_name = nullptr,
    ::flatbuffers::Offset<silent_storm::save::fb::Mission> mission = 0,
    const std::vector<::flatbuffers::Offset<silent_storm::save::fb::Unit>> *units = nullptr,
    uint64_t rng_seed = 0,
    const std::vector<::flatbuffers::Offset<silent_storm::save::fb::KeyValue>> *extras = nullptr) {
  auto slot_name__ = slot_name ? _fbb.CreateString(slot_name) : 0;
  auto units__ = units ? _fbb.CreateVector<::flatbuffers::Offset<silent_storm::save::fb::Unit>>(*units) : 0;
  auto extras__ = extras ? _fbb.CreateVector<::flatbuffers::Offset<silent_storm::save::fb::KeyValue>>(*extras) : 0;
  return silent_storm::save::fb::CreateSave(
      _fbb,
      schema_version,
      timestamp_unix,
      slot_name__,
      mission,
      units__,
      rng_seed,
      extras__);
}

inline const silent_storm::save::fb::Save *GetSave(const void *buf) {
  return ::flatbuffers::GetRoot<silent_storm::save::fb::Save>(buf);
}

inline const silent_storm::save::fb::Save *GetSizePrefixedSave(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<silent_storm::save::fb::Save>(buf);
}

inline const char *SaveIdentifier() {
  return "SSV1";
}

inline bool SaveBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SaveIdentifier());
}

inline bool SizePrefixedSaveBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SaveIdentifier(), true);
}

template <bool B = false>
inline bool VerifySaveBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<silent_storm::save::fb::Save>(SaveIdentifier());
}

template <bool B = false>
inline bool VerifySizePrefixedSaveBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<silent_storm::save::fb::Save>(SaveIdentifier());
}

inline const char *SaveExtension() {
  return "sav";
}

inline void FinishSaveBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<silent_storm::save::fb::Save> root) {
  fbb.Finish(root, SaveIdentifier());
}

inline void FinishSizePrefixedSaveBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<silent_storm::save::fb::Save> root) {
  fbb.FinishSizePrefixed(root, SaveIdentifier());
}

}  // namespace fb
}  // namespace save
}  // namespace silent_storm

#endif  // FLATBUFFERS_GENERATED_SAVEV1_SILENT_STORM_SAVE_FB_H_
