"""Generate an 8x16 ASCII bitmap font atlas for the Phase 1.5 r4 glyph relay.

Outputs a C header file with two arrays:
  - kGlyphAtlasBgra[]  : 128x128 BGRA8 pixels (LE; 0x00BBGGRR on disk)
  - <none else needed; UVs are computed at draw time>

Layout: 16 columns × 8 rows of 8x16 glyph cells, ASCII codes 32..159 mapped to
indices 0..127.  Cell (idx) is at u = (idx % 16) * 8, v = (idx / 16) * 16.

Renders via PIL with Consolas at 14pt — produces real, readable glyphs we can
sample with bilinear/nearest in ss_ui.
"""

from PIL import Image, ImageDraw, ImageFont

CELL_W = 8
CELL_H = 16
COLS   = 16
ROWS   = 8
ATLAS_W = CELL_W * COLS    # 128
ATLAS_H = CELL_H * ROWS    # 128

font = ImageFont.truetype("consola.ttf", 14)

# Build 1-channel atlas first (white-on-black coverage).
img = Image.new("L", (ATLAS_W, ATLAS_H), 0)
drw = ImageDraw.Draw(img)

for idx in range(128):
    code = 32 + idx
    if code > 126:
        continue
    ch = chr(code)
    cx = (idx % COLS) * CELL_W
    cy = (idx // COLS) * CELL_H
    # Center each glyph within its cell.  Consolas at 14pt advance is ~7 px.
    drw.text((cx, cy - 1), ch, fill=255, font=font)

# Optional: also render a horizontal grid line between rows for debug visibility.
# (commented out — keep atlas clean for sampling)

pixels = list(img.getdata())

# Emit as BGRA8: white where coverage>0, fully transparent elsewhere.
# This lets the shader (texture * color) shade per-vertex color through the
# glyph coverage (alpha == coverage).
header = []
header.append("// AUTO-GENERATED by port/scripts/gen_glyph_atlas.py — do not edit.")
header.append("// 128x128 BGRA8 ASCII glyph atlas (8x16 per cell, 16 cols x 8 rows).")
header.append("// Cell index = (ascii_code - 32); cell at u=(idx%16)*8, v=(idx/16)*16.")
header.append("#pragma once")
header.append("#include <cstdint>")
header.append("constexpr int kGlyphAtlasW    = 128;")
header.append("constexpr int kGlyphAtlasH    = 128;")
header.append("constexpr int kGlyphCellW     = 8;")
header.append("constexpr int kGlyphCellH     = 16;")
header.append("constexpr int kGlyphAtlasCols = 16;")
header.append("constexpr int kGlyphAtlasRows = 8;")
header.append("constexpr uint32_t kGlyphAtlasBgra[128*128] = {")
line = []
for i, p in enumerate(pixels):
    # BGRA layout in memory for BGRA8 = (B,G,R,A) ascending bytes.
    # We want white glyphs with coverage as alpha → 0xAARRGGBB little-endian
    # word: 0x{A}{R}{G}{B}.  bgfx::TextureFormat::BGRA8 reads the 32-bit word
    # little-endian as (B,G,R,A) on x86, so the literal we want is
    # (A<<24) | (R<<16) | (G<<8) | (B).
    a = p
    r = g = b = 255 if p > 0 else 0
    w = (a << 24) | (r << 16) | (g << 8) | b
    line.append(f"0x{w:08x}u")
    if len(line) >= 12:
        header.append(",".join(line) + ",")
        line = []
if line:
    header.append(",".join(line) + ",")
header.append("};")

out = "\n".join(header) + "\n"

import os
out_path = os.path.join(os.path.dirname(__file__), "..", "src", "renderer", "glyph_atlas_data.h")
out_path = os.path.normpath(out_path)
with open(out_path, "w", encoding="utf-8") as f:
    f.write(out)
print("wrote", out_path, "bytes:", len(out))
